# 2024 Nature paper
# TOP 38036767 R. HA...  -1 i 2024    14  0  75 au[22](Audrey Lee)
# TITLE: BCG vaccination stimulates integrated organ immunity by feedback 
#        of the adaptive immune response to imprint prolonged
#        innate antiviral resistance
# PubMed: https://pubmed.ncbi.nlm.nih.gov/38036767/
# Nature: https://www.nature.com/articles/s41590-023-01700-0
#
# Data Availability
#   https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE244126
#   Samples:
#     GSM7807682Lung, D0, rep 1
#       SRA: SRX21898392
#       SRR:  SRR26186565
#       SRR: 
#   
#
# Run         | # of Spots  | # of Bases | Size  |Published
# ------------|-------------|------------|-------|----------
# SRR26186565 | 114,895,299 | 15.9G      | 4.8Gb |2023-12-04
# SRR26186566 | 115,135,212 | 15.9G      | 4.7Gb |2023-12-04
#
#     GSM7807683Lung, D21, rep 1
# SRR26186565
#

# https://github.com/ncbi/sra-tools/wiki/HowTo:-fasterq-dump
download:
	fasterq-dump -p SRR26186565
