REF := /data/share/refs/SGD/saccharomyces_cervisiae.fa
BAM0 := /data/share/OMICS/wk06/alns/SF_aer.sorted.bam
BAM1 := /data/share/OMICS/wk06/alns/SF_ann.sorted.bam
BAM2 := /data/share/OMICS/wk06/alns/OGstrain.sorted.bam
# bcftools mpileup -r chrIII -Ou -f
bam:
	find ../wk06 -name '*.sorted.bam'
