REF_DIR := /data/share/refs/pfalciparum
REF_FNA := $(REF_DIR)/GCF_000002765.6_GCA_000002765_genomic.fna.gz
REF_GTF := $(REF_DIR)/GCF_000002765.6_GCA_000002765_genomic.gtf.gz
REF_GFF := $(REF_DIR)/GCF_000002765.6_GCA_000002765_genomic.gff.gz
