DIR_PROJ := /home/jupyter-sb4476/projects/sbCRISPRSCREEN/
#$(DIR_PROJ)/02.reads_20nt/SRR25648809_DMSO_20nt.fastq
REF := $(DIR_PROJ)/00.ref/HS.GRCh38
#LRA is latenct reversal agent treatment
#DMSO is control no treatment
READ_LRA00 := $(DIR_PROJ)/01.reads/SRR25648800_LRA.fastq.gz
READ_DMSO01 := $(DIR_PROJ)/01.reads/SRR25648801_DMSO.fastq.gz
READ_LRA08 := $(DIR_PROJ)/01.reads/SRR25648808_LRA.fastq.gz
READ_DMSO09 := $(DIR_PROJ)/01.reads/SRR25648809_DMSO.fastq.gz

