DIR_PROJ := /home/jupyter-sb4476/projects/sbCRISPRSCREEN/
$(DIR_PROJ)/02.reads_20nt/SRR25648809_DMSO_20nt.fastq
$(DIR_PROJ)/00.ref/HS.GRCh38
$(DIR_PROJ)/01.reads/muxed.stats.tsv
$(DIR_PROJ)/01.reads/SRR25648809_DMSO.fastq.gz
$(DIR_PROJ)/01.reads/SRR25648800_LRA.fastq.gz
$(DIR_PROJ)/01.reads/SRR25648801_DMSO.fastq.gz
$(DIR_PROJ)/01.reads/SRR25648808_LRA.fastq.gz
